import Link from "next/link";
import { getProducts, getProjects } from "@/lib/data";
import ProductCard from "@/components/ProductCard";
import ProjectCard from "@/components/ProjectCard";
import WorkGallery from "@/components/WorkGallery";
export const dynamic = "force-dynamic";
export default async function Home(){ const products=await getProducts(); const projects=await getProjects(); return <>
<section style={{minHeight:620,display:"grid",placeItems:"center",background:"linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.25)),url('https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1800&q=85') center/cover",color:"#fff"}}><div className="container"><div className="hero-content" style={{maxWidth:700}}><p className="hero-kicker" style={{color:"#facc15",fontWeight:800}}>CUSTOM MS & S.S. FABRICATION</p><h1 className="hero-title" style={{fontSize:"clamp(44px,7vw,78px)",lineHeight:1,margin:"10px 0 25px"}}>Metalwork made to measure.</h1><p className="hero-copy" style={{fontSize:20,color:"#e5e7eb"}}>Railings, grills, gates, shutters, canopies and cable trays — measured, fabricated, fitted and finished by one team.</p><div className="hero-actions" style={{display:"flex",gap:12,marginTop:28,flexWrap:"wrap"}}><Link className="btn btn-primary" href="/contact?type=quote">Get a Quote</Link><Link className="btn" style={{border:"1px solid #fff"}} href="/projects">See Our Work</Link></div></div></div></section>
<section className="section"><div className="container"><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"end",marginBottom:28}}><div><p style={{color:"#ca8a04",fontWeight:800}}>WHAT WE FABRICATE</p><h2>Custom products</h2></div><Link href="/products">View all →</Link></div><div className="grid-auto">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p}/>)}</div></div></section>
<section className="section" style={{background:"#f7f7f5"}}><div className="container"><p style={{color:"#ca8a04",fontWeight:800}}>OUR SERVICES</p><h2>Complete metalwork solutions</h2><div className="grid-auto" style={{marginTop:28}}>{["Site Measurement","Steel Fabrication","Welding & CNC Cutting","Fitting & Installation"].map(x=><div className="card" style={{padding:28}} key={x}><h3>{x}</h3><p>Accurate workmanship and professional execution from workshop to site.</p></div>)}</div></div></section>
<section className="section"><div className="container"><p style={{color:"#ca8a04",fontWeight:800}}>PROVEN TRACK RECORD</p><h2>Selected projects</h2><div className="grid-auto" style={{marginTop:28}}>{projects.map(p=><ProjectCard key={p.id} p={p}/>)}</div></div></section>
<WorkGallery />
<section className="section" style={{background:"#111827",color:"#fff"}}><div className="container" style={{textAlign:"center"}}><h2>Planning a railing, gate or shutter?</h2><p style={{color:"#d1d5db"}}>Send your requirement and get a quotation.</p><Link className="btn btn-primary" href="/contact?type=quote">Request a Quote</Link></div></section></> }
